### PR TITLE
Scala 2.12.1 support

### PR DESCRIPTION
**Pull request by golem131**
* Update to Scala 2.11.8

* Update to Scala 2.12.1

* Update sbt to 0.13.13

* Update Json4s to 3.5.0

* Update scalatest to 3.0.1

* Update scalacheck to 1.13.4

### CODE REVIEW

**Comment by ngbinh** [comment]
please consider merging this.

**Comment by sarahgerweck** [comment]
I mean this with no snark: @garyKeorkunian do you intend to continue to maintain this project? (The lack of commits seems to suggest the answer may be "no.") If you do intend to keep it alive, it's getting to have been a long time to not cut a Scala 2.12 when there's a working PR.

It's perfectly fine if you _don't_ have the time or interest to continue basic maintenance like this. If that's the case, I respectfully suggest that you put a comment to that effect at the top of the README so people can make an informed decision about whether to use this library.

**Comment by darkfrog26** [comment]
If there's enough interest in someone taking over maintenance of this project I might be willing if there's no one else.  I need the 2.12 release for one of my projects, and I don't like relying on projects without support.

**Comment by cquiroz** [comment]
I'd be more than happy to maintain it as well

**Comment by darkfrog26** [comment]
If no one has any objection to it being published under "com.outr" (my company name) then I'd be happy to take over.  Now, to clarify here, OUTR would not own the project, just be a steward.  It would remain entirely open-source with the same license it has today.

**Comment by ngbinh** [comment]
no objection here! I can also help if needed.

**Comment by darkfrog26** [comment]
If you look at my GitHub profile, you'll see I'm very active and consistent, so mostly I'd just merge PRs (that are upvoted), do releases, and some possible cleanup.

**Comment by darkfrog26** [comment]
@cquiroz you have any problems with me forking it to the OUTR organization?  I'd definitely welcome any contributions.

**Comment by vitorsvieira** [comment]
As this is a @typelevel project I think it should sit under their flag/org.

**Comment by cquiroz** [comment]
@vitorsvieira That is a valid question, perhaps we can ask at @typelevel if they have dealt with this earlier. I'll ask a contact of mine about it

**Comment by darkfrog26** [comment]
@vitorsvieira that's a very good point, but how do we get them to take the project on?  I certainly don't have access to publish under their organization. ;)

**Comment by vitorsvieira** [comment]
I'm putting on gitter typelevel/general

**Comment by milessabin** [comment]
FYI, I mailed @garyKeorkunian on the e-mail address that he originally contacted me on about Squants becoming a Typelevel project and I haven't received a reply nine days later. I don't know Gary personally so I don't know if we should be concerned about his well-being ... I think we should be considerate because we have no idea what circumstances might have lead to him not responding.

Nevertheless, I think at this point it would be appropriate to fork to continue publishing the library. @garyKeorkunian asked to be considered for Typelevel membership, so I think it would be reasonable to fork into the Typelevel github organization and publish under the "org.typelevel" organization id.

We can review the situation if and when @garyKeorkunian gets back in contact.

**Comment by darkfrog26** [comment]
@milessabin I have no problem with any of that except waiting an undefined amount of time for Gary to respond. How do we proceed if the community want to move forward, but you still have no response from the original creator?

**Comment by milessabin** [comment]
See #139.

**Comment by garyKeorkunian** [comment]
My apologies to everyone for going dark for a bit.  I'm happy to say nothing bad happened to me; just a bit out of touch for while.

This PR has been merged and the Scala 2.12 artifacts for 0.7.1-SNAPSHOT have been published.

Also, I have added darkfrom26 and ngbinh as collaborators so I'm won't need to be a blocker here.  Please let me know if others would like to join as well.

Other services that are required to build and publish Squants are Travis and Sonatype.  I'm not sure how to grant access to others on these platforms, but I am happy to do that as well (some advice needed).

A few months back I changed jobs and at the new gig we have no need for this library.  So I expect my lack of attention and contributions may continue.  

@milessabin if you would like to fork this over to the Typelevel account, that would be fine with me as well.

Again, my apologies to everyone for blocking your progress.

**Comment by darkfrog26** [comment]
@garyKeorkunian thanks for the response.  Great library and I'm happy to help out as I can.  I agree that moving to Typelevel is probably a good measure to allow development to progress.

**Comment by cquiroz** [comment]
Thanks, and I'm happy your doing fine. Any chance of a non-SNAPSHOT release soon?

**Comment by milessabin** [comment]
@garyKeorkunian glad to hear that everything is OK :-)

I think if the consensus is that moving to the Typelevel organization is the best option we should do that. Now that @garyKeorkunian is back in the loop we can consider transferring this repo rather than forking it ... the benefit of doing that is that PR and issue history is preserved.

@garyKeorkunian, if you'd like to do that you can go to the repo "Settings" and hit the "Transfer" button at the bottom of the page. If you transfer to the Typelevel organization I should get a notification and will be able to accept the transfer.

**Comment by garyKeorkunian** [comment]
@milessabin, I tried that, but got the following message:

You don’t have the permission to create repositories on typelevel

Also, I can transfer ownership of the squants.com and squants.org domains, if you think that appropriate.

**Comment by derekmorr** [comment]
Gary,

I'm happy to be added as a collaborator as well, since I've submitted PRs to squants.

Derek

**Comment by milessabin** [comment]
@garyKeorkunian ahh ... right. You could do it if I made you a member of the Typelevel organization, or you could transfer the repo to me and then I could transfer it to Typelevel. Whichever works for you :-)

**Comment by milessabin** [comment]
Apropos the domains, I think that's something the project stakeholders should discuss ... the domains belong with this project rather than Typelevel.

**Comment by garyKeorkunian** [comment]
@milessabin I'd love to be a member.

**Comment by derekmorr** [comment]
Same.

**Comment by cquiroz** [comment]
Do the new maintainers / collaborators of the old repo automatically become maintainers / collaborators on the new one at typeleve?

**Comment by milessabin** [comment]
I think yes if the repo ownership is transferred. But even if not it's easily fixed after the fact.

**Comment by cquiroz** [comment]
Seems to work, I got rights to merge commits on the new repo

**Pull request merged**
